name: Deploy
on:
  push:
    branches: dev
  pull_request:
    branches: dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_DOMAIN: ${{ secrets.NEXT_PUBLIC_DOMAIN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: pnpm/action-setup@v4
        with:
          version: 9 # 或您使用的 pnpm 版本
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install step
        run: "pnpm install"

      - name: Build step
        run: |
          cp .env.example .env
          "pnpm build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "karlorz-next-hono-l-12"
          entrypoint: "jsr:@deno/nextjs-start"
          root: "."
          include: .next, public
          
